### ISSUE TITLE
Empty Result

### ISSUE THREAD

**Issue by faizankhalil007** [emastra/google-shopping-scraper-puppeteer#21]
Hi
I'm using this solution with APIFY, I'm using this with PHP CURL but when the page stop loading it didn't display anything just a blank page, here is my curl
$data = array(
    "queries" => array("tee set"),
    "countryCode" => "us",
    "maxPostCount"=>15,
    "isAdvancedResults"=>false
);
$data_json = json_encode($data);

echo "<h1>Invoking Apify API with:</h1>";
echo "<pre>\n".$data_json."</pre>";
echo "<br><br>";
$agent = 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)';
$ch = curl_init('https://api.apify.com/v2/actor-tasks/PmodKHBnVE6Qv1AAL/run-sync?token=JUST_CHANGED');
curl_setopt($ch, CURLOPT_USERAGENT, $agent);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
curl_setopt($ch, CURLOPT_POSTFIELDS, $data_json);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
        'Content-Type: application/json',
        'Content-Length: ' . strlen($data_json))
);
$result_json = curl_exec($ch);
print_r($result_json);
echo "<h1>Result:</h1>";
echo "<pre>\n".$result_json."</pre>";

can anyone here please let me know which thing is missing? In the APIFY panel it showing results.

**Comment by pocesar** [comment]
this is fixed by using `run-sync-get-dataset-items` endpoint
